name: hetimagl
version: 0.0.1
description: A minimal command-line application.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  hetima:
    path: /Users/kiyohiro/dart/git/dart_hetimalib
dev_dependencies:
  unittest: any
